# Generated by Django 2.1.7 on 2019-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankstock',
            name='latitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodbankstock',
            name='longitude',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodbankstock',
            name='units_of_blood',
            field=models.IntegerField(default=0),
        ),
    ]
